package com.example.collectorvk.model;


public enum LifeCycle {
    REG,
    MAIN_MENU,
    GROUP_MENU,
    MAIN_GROUP_SETTINGS,
    POSTING_GROUP_SETTINGS,
    WAIT_INPUT_LINK_VK_GROUP,
    WAIT_INPUT_TOKEN_USER,
    WAIT_INPUT_LINK_POSTING_GROUP,
    REG_POSTING_GROUP,
    WAIT_INPUT_POSTING_GROUP,
    WAIT_INPUT_POSTING_GROUP_SETTINGS,
    WAIT_INPUT_POSTING_GROUP_DELETE
}
